<?php

/**
 * Country Code: ISO 3166 2-letter code
 *
 * The # characters will be replaced for \d
 * The @ characters will be replaced for [a-zA-Z]
 * The * characters will be replaced for [a-zA-Z0-9]
 */
return [
    'AF' => array('/^####$/'),                     
    'AL' => array('/^####$/'),
    'DZ' => array('/^#####$/'),                     
    'AS' => array('/^#####$/'),                     
    'AD' => array('/^AD###$/'),
    'AO' => array(),                            
    'AI' => array(),                            
    'AQ' => array(),                            
    'AG' => array(),                            
    'AR' => array('/^####$/', '/^@####@@@$/'),          
    'AM' => array('/^####$/'),                  //@todo missing codes in codes.php file
    'AW' => array(),                            
    'AU' => array('/^####$/'),                     
    'AT' => array('/^####$/'),                     
    'AZ' => array('/^######$/', '/^####$/'),    //@todo missing codes in codes.php file
    'BS' => array(),                            
    'BH' => array(),                           
    'BD' => array('/^####$/'),                     
    'BB' => array('/^BB#####$/'),
    'BY' => array('/^######$/'),                //@todo missing codes in codes.php file
    'BE' => array('/^####$/'),                     
    'BZ' => array(),                           
    'BJ' => array(),                          
    'BM' => array('/^@@ ##$/'),                 //@todo missing codes in codes.php file
    'BT' => array(),                        
    'BO' => array(),                         
    'BA' => array('/^#####$/'),                 //@todo missing codes in codes.php file
    'BW' => array(),                          
    'BV' => array(),                         
    'BR' => array('/^#####-###$/', '/^#####$/'),      
    'IO' => array(),                           
    'BN' => array('/^@@####$/'),                //@todo missing codes in codes.php file
    'BG' => array('/^####$/'),                    
    'BF' => array(),                          
    'BI' => array(),                        
    'KH' => array('/^#####$/'),                 //@todo missing codes in codes.php file
    'CM' => array(),                           
    'CA' => array('/^@#@ #@#$/', '/^@#@ #@$/'), //@todo missing codes in codes.php file
    'CV' => array('/^####$/'),                  //@todo missing codes in codes.php file
    'KY' => array('/^KY#-####$/'),              //@todo missing codes in codes.php file
    'CF' => array(),                         
    'TD' => array(),                          
    'CL' => array('/^#######$/'),               //@todo missing codes in codes.php file
    'CN' => array('/^######$/'),                //@todo missing codes in codes.php file
    'CX' => array(),                         
    'CC' => array(),                         
    'CO' => array('/^#####$/'),                 //@todo missing codes in codes.php file
    'KM' => array(),                           
    'CD' => array(),                          
    'CG' => array(),                       
    'CK' => array(),
    'CR' => array('/^#####$/'),                 //@todo missing codes in codes.php file
    'CI' => array(),                         
    'HR' => array('/^#####$/'),                    
    'CU' => array('/^#####$/'),                 //@todo missing codes in codes.php file
    'CY' => array('/^####$/'),                  //@todo missing codes in codes.php file
    'CZ' => array('/^### ##$/'),                   
    'DK' => array('/^####$/'),                     
    'DJ' => array(),                           
    'DM' => array(),                          
    'DO' => array('/^#####$/'),                    
    'TL' => array(),                           
    'EC' => array('/^######$/'),                //@todo missing codes in codes.php file
    'EG' => array('/^#####$/'),                 //@todo missing codes in codes.php file
    'SV' => array('/^####$/'),                  //@todo missing codes in codes.php file
    'GQ' => array(),                            
    'ER' => array(),                            
    'EE' => array('/^#####$/'),                 //@todo missing codes in codes.php file
    'ET' => array('/^####$/'),                  //@todo missing codes in codes.php file
    'FK' => array('/^FIQQ 1ZZ$/'),              //@todo missing codes in codes.php file
    'FO' => array('/^###$/'),                    
    'FJ' => array(),                           
    'FI' => array('/^#####$/'),                   
    'FR' => array('/^#####$/'),                    
    'FX' => array(),                           
    'GF' => array('/^#####$/'),                   
    'PF' => array('/^#####$/'),                 //@todo missing codes in codes.php file
    'TF' => array(),                           
    'GA' => array(),                         
    'GM' => array(),                            
    'GE' => array('/^####$/'),                  //@todo missing codes in codes.php file
    'DE' => array('/^#####$/'),                   
    'GH' => array(),                           
    'GI' => array(),                           
    'GR' => array('/^#####$/', '/^### ##$/'),    //@todo missing codes in codes.php file
    'GL' => array('/^####$/'),                     
    'GD' => array(),                           
    'GP' => array('/^#####$/'),                   
    'GU' => array('/^#####$/'),                     
    'GT' => array('/^#####$/'),                     
    'GN' => array(),                           
    'GW' => array('/^####$/'),                  //@todo missing codes in codes.php file
    'GY' => array(),                           
    'HT' => array('/^####$/'),                  //@todo missing codes in codes.php file
    'HM' => array(),
    'HN' => array('/^#####$/'),                 //@todo missing codes in codes.php file
    'HK' => array(),                          
    'HU' => array('/^####$/'),                    
    'IS' => array('/^###$/'),                   
    'IN' => array('/^######$/'),                   
    'ID' => array('/^#####$/'),                 //@todo missing codes in codes.php file
    'IR' => array('/^#####$/'),                 //@todo missing codes in codes.php file
    'IQ' => array('/^#####$/'),                 //@todo missing codes in codes.php file
    'IE' => array(),                           
    'IL' => array('/^#####$/'),                 //@todo missing codes in codes.php file
    'IT' => array('/^#####$/'),                     
    'JM' => array('/^JM@@@##$/'),                   
    'JP' => array('/^###-####$/', '/^#######$/'),//@todo missing codes in codes.php file
    'JO' => array('/^#####$/'),                  //@todo missing codes in codes.php file
    'KZ' => array('/^######$/'),                 //@todo missing codes in codes.php file
    'KE' => array('/^#####$/'),                  //@todo missing codes in codes.php file
    'KI' => array(),                           
    'KW' => array('/^#####$/'),                  //@todo missing codes in codes.php file
    'KG' => array('/^######$/'),                 //@todo missing codes in codes.php file
    'LA' => array('/^#####$/'),                  //@todo missing codes in codes.php file
    'LV' => array('/^####$/'),                   //@todo missing codes in codes.php file
    'LB' => array('/^####$/'),                   //@todo missing codes in codes.php file
    'LS' => array('/^###$/'),                    //@todo missing codes in codes.php file
    'LR' => array('/^####$/'),                   //@todo missing codes in codes.php file
    'LY' => array('/^#####$/'),                  //@todo missing codes in codes.php file
    'LI' => array('/^####$/'),                     
    'LT' => array('/^#####$/'),                     
    'LU' => array('/^L-####$/'),
    'MO' => array(),                          
    'MK' => array('/^####$/'),                     
    'MG' => array('/^###$/'),                    //@todo missing codes in codes.php file
    'MW' => array(),                          
    'MY' => array('/^#####$/'),                    
    'MV' => array('/^####$/', '/^#####$/'),      //@todo missing codes in codes.php file
    'ML' => array(),                        
    'MT' => array('/^@@@ ####$/'),               //@todo missing codes in codes.php file
    'MH' => array('/^#####$/'),                   
    'MQ' => array('/^#####$/'),                     
    'MR' => array(),                           
    'MU' => array(),                            
    'YT' => array('/^#####$/'),                    
    'MX' => array('/^#####$/', '/^####$/'),             
    'FM' => array('/^#####$/'),                  //@todo missing codes in codes.php file
    'MD' => array('/^MD-####$/'),
    'MC' => array('/^#8000$/', '/^#####$/'),      //@todo missing codes in codes.php file
    'MN' => array('/^#####$/', '/^######$/'),     //@todo missing codes in codes.php file
    'ME' => array('/^#####$/'),                   //@todo missing codes in codes.php file
    'MS' => array(),                           
    'MA' => array('/^#####$/'),                   //@todo missing codes in codes.php file
    'MZ' => array('/^#####$/'),                   //@todo missing codes in codes.php file
    'MM' => array('/^#####$/'),                   //@todo missing codes in codes.php file
    'NA' => array(),                            
    'NR' => array(),                           
    'NP' => array('/^#####$/'),                    //@todo missing codes in codes.php file
    'NL' => array('/^#### @@$/', '/^####$/', '/^####@@$/'), //@todo missing some postal code cases apparently
    'AN' => array(),                           
    'NC' => array('/^#####$/'),                    //@todo missing codes in codes.php file
    'NZ' => array('/^####$/'),                     
    'NI' => array('/^###-###-#$/'),               //@todo missing codes in codes.php file
    'NE' => array('/^####$/'),                    //@todo missing codes in codes.php file
    'NG' => array('/^######$/'),                  //@todo missing codes in codes.php file
    'NU' => array(),                           
    'NF' => array(),                            
    'KP' => array(),                            
    'MP' => array('/^#####$/'),                    
    'NO' => array('/^####$/'),                    
    'OM' => array('/^###$/'),                      //@todo missing codes in codes.php file
    'PK' => array('/^#####$/'),                    
    'PW' => array('/^#####$/'),                    //@todo missing codes in codes.php file
    'PS' => array(),                            
    'PA' => array(),                           
    'PG' => array('/^###$/'),                      //@todo missing codes in codes.php file
    'PY' => array('/^####$/'),                     //@todo missing codes in codes.php file
    'PE' => array('/^##$/'),                       //@todo missing codes in codes.php file
    'PH' => array('/^####$/'),                      
    'PN' => array(),                           
    'PL' => array('/^##-###$/'),                    
    'PT' => array('/^####-###$/', '/^####$/'),          
    'PR' => array('/^#####$/'),                     
    'QA' => array(),                            
    'RE' => array('/^#####$/'),                     
    'RO' => array('/^######$/'),                   
    'RU' => array('/^######$/'),                   
    'RW' => array(),                           
    'KN' => array(),                          
    'LC' => array(),                         
    'VC' => array(),                         
    'WS' => array('/^#####$/'),                     //@todo missing codes in codes.php file
    'SM' => array('/^#####$/'),                     
    'ST' => array(),                            
    'SA' => array('/^#####$/'),                     //@todo missing codes in codes.php file
    'SN' => array(),                            
    'RS' => array('/^#####$/'),                     //@todo missing codes in codes.php file
    'SC' => array(),                            
    'SL' => array(),                            
    'SG' => array('/^######$/'),                    //@todo missing codes in codes.php file
    'SK' => array('/^### ##$/'),                    
    'SI' => array('/^####$/'),                      
    'SB' => array(),                           
    'SO' => array(),                            
    'ZA' => array('/^####$/'),                      
    'GS' => array(),                            
    'KR' => array('/^###-###$/'),                   //@todo missing codes in codes.php file
    'ES' => array('/^#####$/'),                     
    'LK' => array('/^#####$/'),                     
    'SH' => array(),                            
    'PM' => array('/^#####$/'),                    
    'SD' => array('/^#####$/'),                     //@todo missing codes in codes.php file
    'SR' => array(),                           
    'SJ' => array('/^####$/'),
    'JE' => array('/^JE#$/'),
    'SZ' => array('/^@###$/'),                      //@todo missing codes in codes.php file
    'SE' => array('/^### ##$/', '/^#####$/'),       //@todo aparentemente faltan los de los espacios
    'CH' => array('/^####$/'),                     
    'SY' => array(),                           
    'TW' => array('/^###$/', '/^#####$/'),          //@todo missing codes in codes.php file
    'TJ' => array('/^######$/'),                    //@todo missing codes in codes.php file
    'TZ' => array(),                            
    'TH' => array('/^#####$/'),                    
    'TG' => array(),                           
    'TK' => array(),                            
    'TO' => array(),                           
    'TT' => array(),                            
    'TN' => array('/^####$/'),                      //@todo missing codes in codes.php file
    'TR' => array('/^#####$/'),                     
    'TM' => array('/^######$/'),                    //@todo missing codes in codes.php file
    'TC' => array('/^TKC@ 1ZZ$/'),                  //@todo missing codes in codes.php file
    'TV' => array(),                            
    'UG' => array(),                            
    'GB' => array('/^@# #@@$/', '/^@** #@@$/', '/^@@#* #@@$/'), //@todo missing codes in codes.php file
    'UA' => array('/^#####$/'),                     //@todo missing codes in codes.php file
    'AE' => array(),                            
    'UM' => array(),                            
    'UY' => array('/^#####$/'),                     
    'US' => array('/^#####$/','/^#####-####$/'),
    'UZ' => array('/^######$/'),                    //@todo missing codes in codes.php file
    'VU' => array(),                            
    'VA' => array('/^00120$/'),                     
    'VE' => array('/^####$/'),                      //@todo missing codes in codes.php file
    'VN' => array('/^######$/'),                    //@todo missing codes in codes.php file
    'VG' => array('/^VG11#0$/'),                    //@todo missing codes in codes.php file
    'VI' => array(),                            
    'WF' => array('/^#####$/'),                     //@todo missing codes in codes.php file
    'EH' => array('/^#####$/'),                     //@todo missing codes in codes.php file
    'YE' => array(),                            
    'ZM' => array('/^#####$/'),                     //@todo missing codes in codes.php file
    'ZW' => array()     
];